Postgres SSL option
chartbrew/chartbrew pull request #130
Opened 2022-07-28 18:38 UTC by theaccordance

## Commit Message

This pull request enhances the database connection options for Chartbrew, allowing for a SSL certificate to be defined as part of the connection parameters.  Reference: https://github.com/chartbrew/chartbrew/issues/129

## Before submitting this PR, I tested this by
* I tested the happy path for my use case, but I did not perform a regression test against other use cases that likely overlap with this changed code.  Un-tested paths I see:  `mysql`, `postgress without ssl`, and `mysql with ssl`

2022-07-28 18:39 UTC, theaccordance commented on .gitignore
> +.idea/
I can revert this if you'd like, it just ignores the project cache that my IDE (webstorm) adds to every project

2022-07-28 18:40 UTC, theaccordance commented on docs/database/README.md
>  ```
If there are other places in the documentation that need to be updated, let me know

2022-07-28 18:42 UTC, theaccordance commented on server/models/config/config.js
> +    cert: process.env.CB_DB_CERT
Side note:  I'm curious what the rational was behind the distinct env vars between production and develop?

2022-07-29 07:48 UTC, razvanilin requested changes
I tested your changes and it works well with my Mysql database.

The only thing that still needs to be updated is the main documentation page as per the previous comment: https://github.com/chartbrew/chartbrew/blob/master/docs/README.md?plain=1#L132

2022-07-29 07:48 UTC, razvanilin commented on .gitignore
> +.idea/
No need, this change is harmless and it might prove useful for future contributors that use webstorm👌

2022-07-29 07:48 UTC, razvanilin commented on docs/database/README.md
>  ```
Yes, there is one more place this needs to be specified: https://github.com/chartbrew/chartbrew/blob/master/docs/README.md?plain=1#L132

There is a table describing all the variables over there

2022-07-29 07:48 UTC, razvanilin commented on server/models/config/config.js
> +    cert: process.env.CB_DB_CERT
This gives the option to run two instances in parallel more easily. Haven't really used it myself in a while so maybe I'll review this at some point to see if it's really needed anymore

2022-07-29 18:37 UTC, theaccordance commented
Remaining documentation page updated, ready for re-review

2022-07-29 21:00 UTC, razvanilin approved these changes
looks good! 👌

2022-07-29 21:00 UTC, merged

2022-07-29 21:01 UTC, razvanilin commented
Many thanks for the PR @theaccordance ❤️

2022-07-30 01:45 UTC, joshmanders commented on .gitignore
> +.idea/
Just an fyi for future you can create a global gitignore for simple stuff like this.