refactor container PasswordReset to functional component
chartbrew/chartbrew pull request #73
Opened 2020-11-02 11:01 UTC by warisanwar

#58 issue

2020-11-02 15:26 UTC, razvanilin requested changes

2020-11-02 15:26 UTC, razvanilin commented on client/src/containers/PasswordReset.js
> +    setSuccess(true);
this should be `setSuccess(false)`

2020-11-02 15:30 UTC, warisanwar commented on client/src/containers/PasswordReset.js
> +    setSuccess(true);
Fixed it! 💯

2020-11-09 13:21 UTC, warisanwar commented
Changes are already done!You can have a final look and merge it.

2020-11-10 00:26 UTC, razvanilin approved these changes
Thanks for the changes! I'll merge this soon

2020-11-11 07:56 UTC, merged